app1/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', views.admin),
    path('login/', views.login_form),
	path('logout/', views.logout_form),
	path('changePass/', views.changePass ),
	path('changepass/', views.changepass ),
    path('logauth/', views.logauth),
    path('email/', views.emailme),
    path('signup/', views.signup),
    path('setconf/', views.setconf),
    path('listuser/', views.listuser),
    path('useredit/', views.useredit),
    path('test/', views.test),
    path('addpass/', views.addpass),
    path('listpass/', views.listpass),
    path('passtest/', views.passtest),
]

site1/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('app1.urls')),
   # path('admin/', admin.site.urls),
]

#if settings.DEBUG:
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Rsetting (models.Model):
  cur_year = models.IntegerField(default=1400,verbose_name='سال جاری')
  start_time = models.IntegerField(default=7,verbose_name='ساعت شروع فعالیت سازمان')
  end_time = models.IntegerField(default=14,verbose_name='ساعت پایان فعالیت سازمان')
  lim_my = models.IntegerField(default=31,verbose_name='محدودیت مرخصی در سال(به روز)')
  lim_mm = models.IntegerField(default=15,verbose_name='محدودیت مرخصی در ماه(به روز)')
  lim_md = models.IntegerField(default=2,verbose_name='محدودیت مرخصی در روز(به ساعت)')
  work_time = models.IntegerField(default=7,verbose_name='ساعت کاری در روز')
  rel_work = models.FloatField(default=6.5,verbose_name='نسبت روز کاری به مرخصی ساعتی')
  signer = models.IntegerField(default=10001,verbose_name='امضاء کننده')
  baygan = models.IntegerField(default=10001,verbose_name='شماره پرسنلی مسئول بایگانی')
  mali = models.IntegerField(default=10001,verbose_name='شماره پرسنلی مدیر امور مالی')
  hozoor = models.IntegerField(default=10001,verbose_name='شماره پرسنلی مسئول حضور و غیاب')
  amoozesh = models.IntegerField(default=10001,verbose_name='شماره پرسنلی مسئول آموزش')
  ranande = models.IntegerField(default=10001,verbose_name='شماره پرسنلی راننده')
  negah1 = models.IntegerField(default=10001,verbose_name='شماره پرسنلی نگهبان 1')
  negah2 = models.IntegerField(default=10001,verbose_name='شماره پرسنلی نگهبان 1')
  negah3 = models.IntegerField(default=10001,verbose_name='شماره پرسنلی نگهبان 1')
  nagah_ezaf = models.IntegerField(default=2,verbose_name='تعداد روزهای اضافه کار ثابت نگهبانان')
  mamooriat =  models.IntegerField(default=10000000,verbose_name='مبلغ هر روز ماموریت به ریال')
  mablagh1 =  models.IntegerField(default=10000000,verbose_name='مبلغ هر روز ماموریت راننده به ریال')
  mablagh2 =  models.IntegerField(default=10000000,verbose_name='مبلغ ثابت براي راننده اول و دوم به ریال')
  dastzarb = models.FloatField(default=1.4,verbose_name=' دستمزد ماهيانه ضربدر')
  dasttaghsim = models.FloatField(default=7.33,verbose_name='تقسيم بر ')
  kharidm = models.IntegerField(default=2,verbose_name='تعداد روز مرخصي قابل خريد')


class Ruser(AbstractUser):
    personeli = models.IntegerField(null=True,unique=True)
    password = models.CharField(max_length=100)
    dastmozd = models.IntegerField(default=7000000)
    mobile = models.CharField(max_length=11,default='')
    def __str__(self):
        return self.username

class StateType(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class PassType(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Pass(models.Model):
    user = models.ForeignKey(Ruser , on_delete=models.CASCADE ,verbose_name='نام کاربری')
    req_date = models.CharField(max_length=10 ,verbose_name='تاریخ  ثبت درخواست')
    pass_type = models.ForeignKey(PassType , on_delete=models.CASCADE ,verbose_name='نوع مرخصی ' )
    start_date = models.CharField(max_length=10 ,verbose_name='تاریخ شروع')
    end_date = models.CharField(max_length=10 ,verbose_name='تاریخ پایان')
    start_time = models.CharField(max_length=10 ,verbose_name='ساعت شروع')
    end_time = models.CharField(max_length=10 ,verbose_name='ساعت پایان')
    reason = models.CharField(max_length=10 ,verbose_name='علت درخواست')
    sick_paper = models.ImageField(upload_to='images', blank=True, null=True ,verbose_name='گواهی درخواست')
    state = models.ForeignKey(StateType , default=3 , on_delete=models.CASCADE ,verbose_name='وضعیت درخواست')
    signer = models.CharField(max_length=10 , default='10001' ,verbose_name='تایید کننده' )
    def __str__(self):
        return self.req_date

app1/forms.py
from django import forms
from .models import Rsetting,Ruser,PassType,Pass,StateType
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        kwargs["label_suffix"] = ""
        super().__init__(*args, **kwargs)
    username=forms.CharField(label='نام کاربری',widget=forms.TextInput(attrs={'class': ' input100' }))
    password1 = forms.CharField(label='گذرواژه',widget=forms.PasswordInput(attrs={'class':"input100"}))
    password2 = forms.CharField(label='تکرار گذرواژه',widget=forms.PasswordInput(attrs={'class': 'input100' }))
    last_name = forms.CharField(label='نام و نام خانوادگی',widget=forms.TextInput(attrs={'class': 'input100' }))
    email = forms.EmailField(label='ایمیل',widget=forms.TextInput(attrs={'class': 'input100' }))
    personeli = forms.IntegerField(label='شماره پرسنلی',widget=forms.NumberInput(attrs={'class': 'input100' }))
    mobile = forms.IntegerField(label='شماره همراه',widget=forms.TextInput(attrs={'class': 'input100' }))
    dastmozd = forms.IntegerField(label='دستمزد',widget=forms.NumberInput(attrs={'class': 'input100' }))
    class Meta:
        model = Ruser
        fields = ['username', 'password1' , 'password2', 'email','last_name','personeli','mobile','dastmozd']

class Rsettingform(forms.ModelForm):
    class Meta:
        model = Rsetting
        fields = "__all__"

class Tpass(forms.ModelForm):
    class Meta:
        model = Pass
        exclude = ('user' , 'signer', 'state' , 'pass_type')

app1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse,Http404
from django.core.mail import send_mail
from django.conf import settings
from django.utils.html import format_html
from .forms import SignupForm,Rsettingform,Tpass
from .models import Rsetting,Ruser,Pass,PassType,StateType
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
import pandas as pd
#import os,shutil,threading,random,string,requests
#import os,shutil,pyotp,threading,cryptocompare,random,string,pyqrcode
#from pytube import YouTube
#from datetime import datetime
#from django.contrib.auth.models import User,Permission
####################################################################
def index(request):
	try:
	    return render (request,'ou.html')
	except:
		raise Http404("Not Found")
####################################################################
def admin(request):
	try:
	    return render (request,'bt.html')
	except:
		raise Http404("Not Found")
####################################################################
def login_form(request):
	return render (request,'login.html')
####################################################################
def logout_form(request):
	logout(request)
	return redirect ('/')
####################################################################
def changePass(request):
	if not request.user.is_authenticated:
		return render (request,'login.html' )
	pass1=request.POST['pass1']
	request.user.set_password(pass1)
	request.user.save()
	#logout(request)
	#return render (request,'login.html')
	return HttpResponse("True", content_type='text/plain')
####################################################################
def logauth(request):
    try:
        if request.method == 'POST':
            #otp_chk=pyotp.TOTP('H4ZT2CIHQM5XO2VUSZPHWTBHMNQBDY3B')
            username=request.POST['username']
            password=request.POST['password']
            #if username=='admin':
            #    if otpcode!=otp_chk.now():
            #        return redirect ('/')
            user = authenticate(request, username=username, password=password)
            if user is not None :
                if username == 'admin' :
                   login(request , user)
                   return redirect ('/admin')
                else:
                   login(request , user)
                   lst=[[1,'a','aa','ac',0],[2,'b','aa','ac',0],[3,'c','aa','ac',1],[4,'d','aa','ac',3],[5,'e','aa','ac',1]]
                   df = pd.DataFrame(lst, columns =['id', 'title', 'link','clas','parent'])
                   return render (request,'ou.html',{'temp' : df})
            else:
                return redirect ('/')
    except:
        return redirect ('/')
    return redirect ('/')

####################################################################
def changepass(request):
    if request.user.username == "admin":
        if request.method == 'POST':
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, 'Your password was successfully updated!')
                return redirect('/admin')
            else:
                messages.error(request, '')
        else:
            form = PasswordChangeForm(request.user)
    return render(request, 'bt.html', {'form': form , 'var1' : 7 })
####################################################################
def emailme(request):
    send_mail(subject='', message=str(''),  from_email=settings.EMAIL_HOST_USER,   recipient_list=['epg900@gmail.com'])
    return HttpResponse("Email Sent")
####################################################################
def signup(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        if request.user.username == "admin":
            if request.method == 'POST':
                    form = SignupForm(request.POST)
                    if form.is_valid():
                        form.save()
                        return render(request, 'bt.html', {'bodytitle':'کاربر ساخته شد','bodytext':'برای ساخت یک کاربر دیگر روی گزینه افزودن کلیک کنید', 'var1' : 5 })
            else:
                    form = SignupForm()
        return render(request, 'bt.html', {'form': form , 'var1' : 6 })
    except:
        return redirect ('/')

####################################################################
def setconf(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        if request.user.username == "admin":
            ins1=Rsetting.objects.all().first()
            signer = Ruser.objects.get(personeli=ins1.signer)
            mali = Ruser.objects.get(personeli=ins1.mali)
            if request.method == 'POST':
                form = Rsettingform(request.POST, instance = ins1)
                if form.is_valid():
                    form.save()
                    return render(request, 'bt.html', {'var1' : 2 , 'bodytitle':'تنظیمات ذخیره شد'})
            else:
                form = Rsettingform(instance = ins1)
        return render(request, 'bt.html', {'form': form , 'var1' : 1 , 'signer' : signer.last_name , 'mali' : mali.last_name })
    except:
        return redirect ('/')

####################################################################
def listuser(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        if request.user.username == "admin":
            userlist=Ruser.objects.exclude(username = "admin")
        return render(request, 'bt.html', {'userlist': userlist , 'var1' : 3 })
    except:
        return redirect ('/')
####################################################################
def useredit(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        if request.user.username == "admin":
            if request.method == 'POST':
                idx = request.POST['idnum']
                ins1=Ruser.objects.get(id = idx)
                form =SignupForm(request.POST , instance = ins1)
                if form.is_valid():
                    form.save()
                    ins1.set_password(request.POST['password1'])
                    ins1.save()
                    #update_session_auth_hash(request, user)  # Important!
                    #messages.success(request, 'Your password was successfully updated!')
                    return redirect('/admin')
            else:
                idx = request.GET['id']
                ins1=Ruser.objects.get(id = idx)
                form =SignupForm(instance = ins1)
                return render(request, 'bt.html', {'form': form , 'var1' : 4 ,'idx' : idx })
        return redirect('/')
    except:
        return redirect ('/')
####################################################################
def addpass(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        if request.method == 'POST':
                form = Tpass(request.POST,initial={'pass_type':1,})
                #form.fields['pass_type'].widget.attrs['readonly'] = True
                if form.is_valid():
                    instance=form.save(commit=False)
                    instance.user=request.user
                    instance.pass_type=PassType.objects.get(id = 1)
                    instance.save()
                    #form.save(commit=False)
                    #form.user=request.user
                    #form.save()
                    return render(request, 'ou.html', {'bodytitle':'افزوده شد','bodytext':'', 'var1' : 2 })
        else:
                form = Tpass(initial={'pass_type':1,})
        return render(request, 'ou.html', {'form': form , 'var1' : 1 })
    except:
        return redirect ('/')
####################################################################
def listpass(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    try:
        passlist=Pass.objects.all()
        return render(request, 'ou.html', {'passlist': passlist , 'var1' : 3 })
    except:
        return redirect ('/')
####################################################################
def passtest(request):
    if not request.user.is_authenticated:
        return redirect ('/')
    if request.user.username == "h.tizhoosh":
        if request.method == 'GET' and request.GET.get("id") is not None and request.GET.get("ok") is not None:
                idx = request.GET['id']
                okn = request.GET['ok']
                #return HttpResponse(idx + " " + okn)
                if okn == '1' :
                    ins1=Pass.objects.get(id = idx)
                    ins1.state=StateType.objects.get(id = 1)
                    ins1.save()
                if okn == '2' :
                    ins1=Pass.objects.get(id = idx)
                    ins1.state=StateType.objects.get(id = 2)
                    ins1.save()
        passlist = Pass.objects.all()
        return render(request, 'ou.html',{'passlist' : passlist , 'var1' : 8 })
    return redirect ('/')


####################################################################
def test(request):

    html_text=format_html("<H1>{}</H1>","<i>test<i>")
    return HttpResponse(html_text)

'''

if request.method == 'POST':
            form = ImageForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return render(request, 'index.html', {'form': form})
        else:
            form = ImageForm()
        context = {'bodytitle':'خوش آمدید','bodytext':'Benvenuto','form': form}
        return render(request, 'index.html', context)

disp=Image.objects.all()
    if request.method == 'POST':
        post1=request.POST['imgid']
        pic=Image.objects.filter(pk=int(post1))

app1/templates/adduser.html
{% extends "login.html" %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated and request.user.username == "admin" %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url({% static 'login/pics/bg-01.jpg' %});">
					<span class="login100-form-title-1">افزودن کاربر</span>
				</div>

					<form id="loadpic"  method="post" enctype="multipart/form-data" action="/signup/" class="login100-form validate-form">
					{% csrf_token %}
							{% for field in form %}
							<div class="form-group validate-input" >
								<span class="label-input100">
								{{ field.label_tag }}
								</span>
								{{ field }}
								<span class="focus-input100"></span>
							</div>
							{% endfor %}
							<div class="container-login100-form-btn">
								<a href="/" class="login100-form-btn">بازگشت</a>
								<button class="login100-form-btn">افزودن</button>
							</div>
					</form>
			</div>
		</div>
	</div>
	{% else %}
	<script>
	    window.location.href = "/";
	</script>
	{% endif %}
{% endblock content %}

app1/templates/changepass.html
{% extends "login.html" %}
{% load static %}
{% block content %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url({% static 'login/pics/bg-01.jpg' %});">
					<span class="login100-form-title-1">   تغییر رمز عبور </span>
				</div>
				<form class="login100-form validate-form"  id="login" method="post" enctype="multipart/form-data" action="/changepass/" >
				    {% csrf_token %}
					        {% for field in form %}
							<div class="form-group" >
								{{ field.label_tag }}
								{{ field}}
							</div>
							{% endfor %}
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">ذخیره</button>
					</div>
				</form>
			</div>
		</div>
	</div>
    {% endblock content %}

app1/templates/ou.html
{% load static %}
{% load ulmenu %}
<!DOCTYPE html>
<html lang="fa">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>سامانه پرسنلی اتاق بازرگانی</title>

	<!-- Font Awesome Icons -->
	<link href="{% static 'bt/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

	<!-- Plugin CSS -->
	<link href="{% static 'bt/css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'persianDatepicker-default.css' %}" />


	<link href="{% static 'bt/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

	<!-- Theme CSS - Includes Bootstrap -->
	<link href="{% static 'bt/css/style.css' %}" rel="stylesheet">



</head>
<body id="page-top" class="rtl">



	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
		<div class="container">
			<a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{% static 'logo.png' %}" alt="" height="36"> <span>  سامانه پرسنلی اتاق بازرگانی </span> </a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto my-2 my-lg-0">
				    {% if request.user.is_authenticated and request.user.username == "h.tizhoosh" %}
				    <li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="/passtest">بررسی درخواستها</a>
					</li>
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="/edituser">مدیریت کاربران</a>
					</li>
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="/signup">افزودن کاربر</a>
					</li>
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> گزارشات <span class="caret"></span></a>
					  <ul class="dropdown-menu">
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
						<li><a href="#" onclick="$('#menu2').val('m');" data-toggle="modal" data-target="#exampleModal" class="nav-link js-scroll-trigger" > </a></li>
					  </ul>
					</li>
					{% endif %}
				</ul>
				<ul class="navbar-nav navbar-right  ml-auto my-2 my-lg-0">
					{% if request.user.is_authenticated %}
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {{request.user.last_name}} <span class="caret"></span></a>
					  <ul class="dropdown-menu">
						<li><a href="/changepass" class="nav-link js-scroll-trigger" > تغییر رمز عبور  </a></li>
						<li role="separator" class="divider"></li>
						<li><a href="/logout" class="nav-link js-scroll-trigger" > خروج  </a></li>
					  </ul>
					</li>
					{% else %}
					<li  class="nav-item" ><a  class="nav-link js-scroll-trigger"  href="/login">ورود</a></li>
					{% endif %}
			    </ul>
			</div>
		</div>
	</nav>

	<section class="page-section bg-dark text-white" id="main">
		<div class="container-fluid">
				{% if request.user.is_authenticated %}
				{% if var1 == 1 %}
				<form  class="row" id="login" method="post" enctype="multipart/form-data" action="/addpass/" >
				    {% csrf_token %}
				            {% for field in form %}
					        <div class="col-md-3 form-group" >
								{{ field.label_tag }}
							</div>
							<div class="col-md-3 form-group" >
								{{ field}}
							</div>
							{% endfor %}
					<div class="col-12 form-group">
					    <button class="btn btn-primary btn-xl ">ذخیره</button>
                    </div>
				</form>
				{% elif var1 == 3 %}
				<div class="table-responsive">
					<table class="table table-bordered table-striped table-hover">
                        <tr>
                        <th>نام کاربری</th>
                        <th>ایمیل</th>
                        <th>نام و نام خانوادگی</th>
                        <th>شماره پرسنلی</th>
                        <th>دستمزد ماهیانه</th>
                        <th></th>
                        </tr>
                        {% for i in passlist %}
                        <tr>
                        <td>{{i.user.last_name}}</td>
                        <td>{{i.pass_type}}</td>
                        <td>{{i.req_date}}</td>
                        <td>{{i.start_date}}</td>
                        <td>{{i.state}}</td>
                        <td><a class="btn btn-primary" href="/usereditform?id={{i.id}}">ویرایش</a></td>
                        </tr>
                        {% endfor %}
                    </table>
				</div>
				{% elif var1 == 8 %}
				<div class="table-responsive">
					<table class="table table-bordered table-striped table-hover">
                        <tr>
                        <th>نام کاربر</th>
                        <th>تاریخ درخواست</th>
                        <th>نام و نام خانوادگی</th>
                        <th>شماره پرسنلی</th>
                        <th>دستمزد ماهیانه</th>
                        <th></th>
                        <th></th>
                        </tr>
                        {% for i in passlist %}
                        <tr>
                        <td>{{i.user.last_name}}</td>
                        <td>{{i.req_date}}</td>
                        <td>{{i.start_date}}</td>
                        <td>{{i.reason}}</td>
                        <td>{{i.state}}</td>
                        <td><a class="btn btn-primary" href="/passtest?id={{i.id}}&ok=1">تایید</a></td>
                        <td><a class="btn btn-danger" href="/passtest?id={{i.id}}&ok=2">عدم تایید</a></td>
                        </tr>
                        {% endfor %}
                    </table>
				</div>
				{% endif %}
                <div class="col-lg-12 align-self-end">
					<h1 class="text-uppercase text-white font-weight-bold">خوش آمدید  {{request.user.last_name}} </h1>
					<br>
					<h4>{{temp}}</h4>
				</div>
				<div class="col-lg-8 align-self-baseline">
					<p class="text-white-75 font-weight-light mb-5">از منوی مربوطه عملیات مورد نطر خود را انتخاب نمایید </p>
					<a class="btn btn-primary btn-xl js-scroll-trigger" href="/addpass">لیست مرخصی</a>
				</div>
                {% else %}
				<div class="col-lg-12 align-self-end">
					<h1 class="text-uppercase text-white font-weight-bold">سایت پرسنلی اتاق بازرگانی</h1>
					</div>
				<div class="col-lg-8 align-self-baseline">
					<p class="text-white-75 font-weight-light mb-5"></p>
					<a class="btn btn-primary btn-xl js-scroll-trigger" href="/login">وارد شوید</a>
				</div>
				{% endif %}
		</div>
	</section>

    <!-- Modal -->
    <div class="modal bottom fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-mdb-backdrop="false" data-mdb-keyboard="true">
      <div class="modal-dialog modal-frame modal-bottom ">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <input type="input" name="menu2" id="menu2" value="" >
            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">...</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              Close
            </button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>



	<!-- Bootstrap core JavaScript -->
	<script src="{% static 'bt/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'bt/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!--<script src="js/jquery-1.10.1.min.js"></script>-->
    <script src="{% static 'persianDatepicker.js' %}"></script>
	<!-- Plugin JavaScript -->
	<script src="{% static 'bt/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
	<script src="{% static 'bt/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

	<!-- Custom scripts for this template -->
	<script src="{% static 'bt/js/creative.min.js' %}"></script>

	<script>
        $(function () {
            $("#id_req_date").persianDatepicker();
            $("#id_start_date").persianDatepicker();
            $("#id_end_date").persianDatepicker();
        });
    </script>

</body>
</html>